### ISSUE TITLE
In 3 column layout, adding content in the middle column in a list causes it to spill over into the 3rd column

### ISSUE THREAD

**Issue by adam-jones-net** [ticlekiwi/API-Documentation-HTML-Template#5]
Love the template but I've hit a problem straight way.  I'm adding simple list content <ul><li> list content to the middle column, but it just overflows into the third dark grey code column.   There is no extra styling at play, I've not altered anything so far.    

I've run over the styles I can see here but can't work out why it doesn't wrap.

**Comment by floriannicolas** [comment]
Hello @arkid, could you link me a visual example of your problem ? maybe a jsfiddle or a screenshot ? 
Maybe I can a find a solution for you.

**Comment by adam-jones-net** [comment]
I've attached a modified version of the index.html file in the package.   All I've done is add a standard list tag element within the initial paragraphs at the top of the page and you will see how these wrap.

![image](https://user-images.githubusercontent.com/3810108/132482481-a085e446-0788-49d7-8a67-ac866ad1995f.png)

[index.txt](https://github.com/ticlekiwi/API-Documentation-HTML-Template/files/7127580/index.txt)

**Comment by floriannicolas** [comment]
Hello @arkid, 
I pushed a fix for your problem. 
You can download latest version (1.0.3) and just change `style.css` file on your project.
Or you can see changes on the last commit [here](https://github.com/ticlekiwi/API-Documentation-HTML-Template/commit/06e66b6e94f0cd780e4deca992a66a672111ddd2).

If you don't see any changes, don't forget to refresh your cache 😉 

Please tell if I have fixed your issue 👍

**Comment by adam-jones-net** [comment]
Amazing thanks!!!
