### ISSUE TITLE
Some more formatting issues found relating to wrapping

### ISSUE THREAD

**Issue by adam-jones-net** [ticlekiwi/API-Documentation-HTML-Template#6]
Hi the screenshot attached shows various things that would be great to make more robust in the CSS.  They are....

1) menus wrap and are not aligned properly on the second line of text
2) the urls for end points don't wrap
3) tables don't deconstruct/wrap

The edited index.html that I took this screenshot from is included.  Hopefully you can see that I haven't done anything odd at all here, it's all very simple standard HTML, I don't think I've introduced a single new html tag that wasn't already in the sample index.html file.

[index.txt](https://github.com/ticlekiwi/API-Documentation-HTML-Template/files/7150352/index.txt)

![image](https://user-images.githubusercontent.com/3810108/133003943-94b2f09f-98bb-4ace-b6d1-07447f4d820a.png)

**Comment by floriannicolas** [comment]
Hello @arkid,
I pushed a 1.0.4 version that will solve your problems.
Please Note every changes : 
- `css/style.css` need to be updated.
- `js/script.js` file need to be updated. (I removed jQuery usage to prefer vanilla js)
- I removed `jQuery` call in `<head>` of `index.html`.
- I updated `Google Font` call in `<head>`of `index.html`, adding `preconnect` rules and fixing `Roboto Condensed` usage. ( now in 3 lines: 21 to 23) : 
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;1,300&family=Source+Code+Pro:wght@300&display=swap" rel="stylesheet"> 
 ```
 
- I updated `data-target` in menu : previously you had:
```html
 <li class="scroll-to-link active" data-target="get-started">
         <a>GET STARTED</a>
 </li>
 ```
 Now you have :
 ```html
 <li class="scroll-to-link active" data-target="content-get-started">
         <a>GET STARTED</a>
 </li>
 ```
 
 - Finally I added a new css class `.central-overflow-x`. You'll need to add it everytime you have an element in central column that overflow on third column. In your case : 
 ```html
<code class="higlighted central-overflow-x">...<code>
```
 ```html
<table class="central-overflow-x">...<table>
```

I hope it will work for you!

**Comment by adam-jones-net** [comment]
Thanks so much for this, really appreciated.  The one thing I still see is that the urls still wrap and adding the central-overflow-x class doesn't seem to work properly.  Also I'd argue that it isn't really the kind of content that should need to scroll, I'd say that it should just wrap.

In this image below I've taken the new codebase and just altered the url to make it longer so you can see how it conflicts with the right column.  
![image](https://user-images.githubusercontent.com/3810108/133058503-4a6079d3-f847-4718-b4f2-c90f822cf81f.png)

**Comment by floriannicolas** [comment]
Hi @arkid,
It's pretty weird because I don't have this problem : 

I've updated `index.html` to have this : 
```html
<p>
    To get characters you need to make a POST call to the following url :<br>
    <code class="higlighted central-overflow-x">http://api.westeros.com/charactercharactercharactercharactercharacter/get</code>
</p>
```
And the url overflow is correctly displayed (with an horizontal scrollbar which isn't displayed because i'm on mac) like this screenshot: 
<img width="1023" alt="Screenshot+2021-09-13+01 31 26" src="https://user-images.githubusercontent.com/3403922/133076317-588bdc87-978b-4450-a790-02d5e49fc610.png">

Could you please give me your browser using this service ?
https://www.whatsmybrowser.org/ 
You'll need to copy the link created, like this : https://www.whatsmybrowser.org/b/HYE1S (it's my browser used for the screenshot)

**Comment by adam-jones-net** [comment]
To be clear, we are seeing the same thing.  With your overflow class
applied it *works *for me as well.
I just don't think that the overflow is appropriate for standard text in
the middle column so was wondering if you can make that text also wrap?

It just seems to me that something like a piece of normal text on a line
surrounded by other text that does wrap ok shouldn't need to scroll and
have this overflow class applied.

Also a user doesn't see the scrollbars unless you mouse over them means
that it isn't clear that the text needs to be scrolled.   So I think it
causes confusion as people could see a url and think it's complete, when
actually you are just seeing only some of it due to the overflow.

**Comment by floriannicolas** [comment]
Oh, I'm sorry, I read too fast. 
I made a commit that might be your solution : 
updating `css/style.css`

You can now use the util class `break-word` like this : 
```html
<p>
    To get characters you need to make a POST call to the following url :<br>
    <code class="higlighted break-word">http://api.westeros.com/charactercharactercharactercharactercharacter/get</code>
</p>
```
With this class, a too long text will be naturally breaked and will continue to the next line, like this screenshot: 

In Chrome
<img width="778" alt="Screenshot+2021-09-13+01 48 39" src="https://user-images.githubusercontent.com/3403922/133078484-ce336969-24d3-4a6b-9fc0-4c6475544509.png">

Please note that css break-word might differ according to your browser. 
In Firefox: 
<img width="952" alt="Screenshot+2021-09-13+01 51 55" src="https://user-images.githubusercontent.com/3403922/133078744-305e9839-5832-463e-9065-6268eabc2dd7.png">

Edit : It's now pushed.

**Comment by adam-jones-net** [comment]
Great thanks!

Adam

**Comment by floriannicolas** [comment]
If this solution is ok for you, can I close the issue ? 

Florian
