### ISSUE TITLE
Highlighted menu item seems to be one item above what is current 

### ISSUE THREAD

**Issue by adam-jones-net** [ticlekiwi/API-Documentation-HTML-Template#7]
This doesn't happen on all my content, but if you load this page I'm working on: 

https://developers.theapartmentnetwork.com/

You will see that if you click "/Availability" in the menu, that it scrolls down but that the item above in the menu is still highlighted.

![image](https://user-images.githubusercontent.com/3810108/133265577-852966f7-28bb-48ca-ad77-55cfa984f170.png)

**Comment by floriannicolas** [comment]
Hello @arkid , glad to see my little work on a project!
I made a small fix for your problem, all you have to do is update `js/script.js` file.
Don't forget to refresh your cache. 
Please let me now if its ok for you!

**Comment by adam-jones-net** [comment]
Thanks so much, seems to work! :)
