### ISSUE TITLE
Is the menu meant to appear on mobiles? 

### ISSUE THREAD

**Issue by adam-jones-net** [ticlekiwi/API-Documentation-HTML-Template#8]
Just to check, if on a mobile in portrait. Odd I see no menu at all. Is that intentional?

It so, as a feature request,  wouldn't it be a good idea to make it slide out and maybe have a burger icon or use the icon already present in the header to activate it?

Thanks for your time

**Comment by floriannicolas** [comment]
Hi @arkid , Yes, menu is actually not displayed on mobile, it's intentional. 
To be precise, menu if hidden if screen width is less than 680px. 

I understand your idea, you're right, a burger will make the deal! 
I'll try to implement it in few days. 
Let's keep this issue open until then! 

Regards.

**Comment by adam-jones-net** [comment]
OK thank you, sounds great :)

**Comment by floriannicolas** [comment]
Hello @arkid , 

I made a new 1.0.5 version, adding : 
- Optional `Version` & `Last updated` infos (inspired by you :wink:)
- Responsive menu with `burger icon` menu button. 

You can give it a try [here](https://ticlekiwi.github.io/API-Documentation-HTML-Template/).

Here the updates: 
- `js/script.js`
- `css/style.css`
- `index.html` > only the `left-menu` changed. I invite you to copy it then replace the `<ul>...</ul>` with yours (finally changing name `API Documentation` by yours).

Note that the new `<div class="content-infos">...</div>` is totally **optional** and doesn't break design if you remove it. 

Please tell me if that was you had in mind! 

Regards.

**Comment by adam-jones-net** [comment]
Hi amazing looks really smart!  One thing; I'm just simulating in chrome with the mobile view of dev tools and it seems that the page doesn't want to scroll up and down?

**Comment by floriannicolas** [comment]
Hi, thank you for the feedback! I fixed it.

New updates: 
- `js/script.js`
- `css/style.css`

You can still try it [here](https://ticlekiwi.github.io/API-Documentation-HTML-Template/) after **clearing your cache**.

**Comment by adam-jones-net** [comment]
Amazing thanks so much for your responses on this! :)   I will implement on my site asap.
